version: '3.8'

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      IS_DEV: ${IS_DEV}
    networks:
      - my_network
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge